stages:
  - build
  - package

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKER_HUB_ACCESS_TOKEN: $DOCKER_HUB_ACCESS_TOKEN
  DOCKER_HUB_REPO_NAME: $DOCKER_HUB_REPO_PLATFORM_FRONTEND
  DOCKER_HUB_IMAGE_REGISTRY: $DOCKER_HUB_IMAGE_REGISTRY
  IMAGE_NAME: $DOCKER_HUB_IMAGE_REGISTRY/$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPO_NAME

build:
  stage: build
  image: node:20-alpine
  script:
    - npm ci
    - npm run simple-build
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_BRANCH'


tag_latest:
  stage: package
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  tags:
    - gitlab-org-docker
  variables:
    IMAGE_LATEST: $IMAGE_NAME:latest
  before_script:
    - |
      echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - |
      docker build -t $IMAGE_LATEST .
      docker push $IMAGE_LATEST
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

tag_hash:
  stage: package
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  tags:
    - gitlab-org-docker
  variables:
    IMAGE_HASH: $IMAGE_NAME:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  before_script:
    - |
      echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - |
      docker build -t $IMAGE_HASH .
      docker push $IMAGE_HASH

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual